name: Attachment Validation Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'server/journalEntryRoutes.ts'
      - 'server/storage/journalEntryStorage.ts'
      - 'server/storage/fileStorage/**'
      - 'test/attachments_validation.test.ts'
      - 'test/attachments_acl.test.ts'
      - 'test/upload_posting_workflow.test.ts'
      - 'server/migrations/20250430_add_je_files_admin_role.ts'
      - 'server/migrations/20250429_add_deleted_at_to_journal_entry_files.ts'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'server/journalEntryRoutes.ts'
      - 'server/storage/journalEntryStorage.ts'
      - 'server/storage/fileStorage/**'
      - 'test/attachments_validation.test.ts'
      - 'test/attachments_acl.test.ts'
      - 'test/upload_posting_workflow.test.ts'
      - 'server/migrations/20250430_add_je_files_admin_role.ts'
      - 'server/migrations/20250429_add_deleted_at_to_journal_entry_files.ts'

jobs:
  attachment-validation-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create test database tables
        run: |
          npm run db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      
      - name: Seed test data
        run: |
          npm run db:seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      
      - name: Start server in background
        run: |
          npm run dev &
          sleep 5 # Wait for server to start
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          
      - name: Run attachment validation tests
        run: |
          npx ts-node test/attachments_validation.test.ts
          npx ts-node test/attachments_acl.test.ts
          npx ts-node test/upload_posting_workflow.test.ts
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db